### ISSUE TITLE
[#1.1] Add habit

### ISSUE THREAD

**Issue by wrrnlim** [CMPUT301F21T30/Habiteer#2]
As a doer, I want to add a habit, giving it a brief title, reason, date to start, and whether it is public or private.

**Comment by geoff-B** [comment]
Tasks:
- [ ] Entry fields:
  - [ ] Enter a name
  - [ ] Enter a date range
  - [ ] Enter days of the week
  - [ ] Enter habit reason
- [ ] Create a Habit object with the entered information
